# Generated by Django 3.2.17 on 2023-02-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_app', '0002_auto_20230202_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesupload',
            name='file',
            field=models.FileField(upload_to='pdf'),
        ),
    ]
